# Generated by Django 4.1.7 on 2023-04-18 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='room',
            field=models.ManyToManyField(related_name='hashtags', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='user',
            field=models.ManyToManyField(related_name='hashtags', to=settings.AUTH_USER_MODEL),
        ),
    ]
